Repository chanzuckerberg/cryoet-data-portal, pull requests merged in 2025-04, with the labels that each got.

#1730 feat: Add Key Photo Captions
  .infra/rdev/values.yaml
  frontend/packages/data-portal/app/components/Dataset/DatasetHeader.tsx
  frontend/packages/data-portal/app/components/Deposition/DepositionHeader.tsx
  frontend/packages/data-portal/app/components/HeaderKeyPhoto.tsx
  frontend/packages/data-portal/app/components/KeyPhoto.tsx
  frontend/packages/data-portal/app/components/KeyPhotoCaption/KeyPhotoCaption.tsx
  frontend/packages/data-portal/app/components/Run/RunHeader.tsx
  frontend/packages/data-portal/app/constants/dataTypes.ts
  frontend/packages/data-portal/app/graphql/getDatasetByIdV2.server.ts
  frontend/packages/data-portal/app/graphql/getRunByIdV2.server.ts
  frontend/packages/data-portal/public/locales/en/translation.json
Labels: stack

#1736 feat: Improve Ground Truth Filter
  .infra/rdev/values.yaml
  frontend/packages/data-portal/app/components/DatasetFilter/IncludedContentsFilterSection.tsx
  frontend/packages/data-portal/app/components/DatasetFilter/constants.ts
  frontend/packages/data-portal/app/components/Filters/BooleanFilter.tsx
  frontend/packages/data-portal/app/components/Filters/FilterSection.tsx
  frontend/packages/data-portal/app/components/Filters/Filters.module.css
  frontend/packages/data-portal/app/components/Filters/GroundTruthAnnotationFilter.tsx
  frontend/packages/data-portal/app/components/RunFilter/RunFilter.tsx
  frontend/packages/data-portal/app/graphql/common.ts
  frontend/packages/data-portal/app/i18n.ts
  frontend/packages/data-portal/app/mocks/Remix.mock.ts
  frontend/packages/data-portal/app/types/filter.ts
  frontend/packages/data-portal/public/locales/en/translation.json
Labels: stack

#1728 docs: Add to changelog for Frames and CTF related changes
  docs/changelog.md
Labels: documentation

#1739 feat: Add Data Summary to Run and Dataset Pages
  .infra/rdev/values.yaml
  frontend/packages/data-portal/app/components/Dataset/DatasetOverview.tsx
  frontend/packages/data-portal/app/components/Dataset/utils.ts
  frontend/packages/data-portal/app/components/Deposition/DepositionMetadataTable.tsx
  frontend/packages/data-portal/app/components/Download/DownloadModal.tsx
  frontend/packages/data-portal/app/components/Download/DownloadOptionsContent.tsx
  frontend/packages/data-portal/app/components/Download/types.ts
  frontend/packages/data-portal/app/components/Download/utils.ts
  frontend/packages/data-portal/app/components/PageHeaderSubtitle.tsx
  frontend/packages/data-portal/app/components/Run/RunHeader.tsx
  frontend/packages/data-portal/app/components/Tooltip.tsx
  frontend/packages/data-portal/app/components/common/CollapsibleDescription/CollapsibleDescription.tsx
  frontend/packages/data-portal/app/components/common/ContentsSummaryTable/ContentsSummaryTable.tsx
  frontend/packages/data-portal/app/components/common/ContentsSummaryTable/constants.ts
  frontend/packages/data-portal/app/context/DownloadModal.context.ts
  frontend/packages/data-portal/app/graphql/getDatasetByIdV2.server.ts
  frontend/packages/data-portal/app/graphql/getRunByIdV2.server.ts
  frontend/packages/data-portal/app/hooks/useDatasetById.ts
  frontend/packages/data-portal/app/hooks/useRunById.ts
  frontend/packages/data-portal/app/routes/datasets.$id.tsx
  frontend/packages/data-portal/app/types/gql/datasetPageTypes.ts
  frontend/packages/data-portal/public/locales/en/translation.json
Labels: stack

#1748 docs: Update cryoet_data_portal_docsite_examples.md
  docs/cryoet_data_portal_docsite_examples.md
Labels: documentation, backport-docs

#1752 fix: Scroll position with filter
  .infra/rdev/values.yaml
  frontend/packages/data-portal/app/components/Filters/MultiInputFilter.tsx
  frontend/packages/data-portal/app/components/Filters/RegexFilter.tsx
  frontend/packages/data-portal/app/components/TablePageLayout/TableHeaderDefinition.tsx
  frontend/packages/data-portal/app/components/TablePageLayout/TablePageLayout.test.tsx
  frontend/packages/data-portal/app/components/TablePageLayout/TablePageLayout.tsx
  frontend/packages/data-portal/app/components/TablePageLayout/components/TablePageTabContent.tsx
  frontend/packages/data-portal/app/components/TablePageLayout/components/components/TableHeader.tsx
  frontend/packages/data-portal/app/components/TablePageLayout/index.ts
  frontend/packages/data-portal/app/components/TablePageLayout/types.ts
  frontend/packages/data-portal/app/hooks/useFilter.ts
  frontend/packages/data-portal/app/routes/browse-data.datasets.tsx
  frontend/packages/data-portal/app/types/filter.ts
  frontend/packages/data-portal/app/utils/revalidate.ts
Labels: stack

#1743 feat: Add Object Id Prefix
  .infra/rdev/values.yaml
  frontend/packages/data-portal/app/components/AnnotationFilter/AnnotationFilter.tsx
  frontend/packages/data-portal/app/components/AnnotationFilter/ObjectIdFilter.tsx
  frontend/packages/data-portal/app/components/AnnotationFilter/ObjectIdFilter/ObjectIdFilter.tsx
  frontend/packages/data-portal/app/components/AnnotationFilter/ObjectIdFilter/PrefixValueContext.tsx
  frontend/packages/data-portal/app/components/DatasetFilter/AnnotationMetadataFilterSection.tsx
  frontend/packages/data-portal/app/components/DatasetFilter/NameOrIdFilterSection.tsx
  frontend/packages/data-portal/app/components/DepositionFilter/DepositionIdFilter.tsx
  frontend/packages/data-portal/app/components/Filters/AuthorFilter.tsx
  frontend/packages/data-portal/app/components/Filters/DropdownFilterButton.tsx
  frontend/packages/data-portal/app/components/Filters/EntityIdFilter.tsx
  frontend/packages/data-portal/app/components/Filters/InputFilter.tsx
  frontend/packages/data-portal/app/components/Filters/MultiInputFilter.tsx
  frontend/packages/data-portal/app/components/Filters/PrefixOptionFilter.tsx
  frontend/packages/data-portal/app/components/Filters/RegexFilter.tsx
  frontend/packages/data-portal/app/components/RunFilter/RunFilter.tsx
  frontend/packages/data-portal/public/locales/en/translation.json
Labels: stack

#1789 fix: filter by non-null alignment method
  .infra/rdev/values.yaml
  frontend/packages/data-portal/app/graphql/getRunByIdV2.server.ts
  frontend/packages/data-portal/app/hooks/useRunById.ts
Labels: stack
